# Generated by Django 4.0.3 on 2022-03-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_post_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
