# Generated by Django 4.0.3 on 2022-03-31 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user_name',
        ),
    ]
